### PR TITLE
feat(control char): add basic control char support

### LINKED ISSUE #138: Support control characters (\n, \r, \b, \t)
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

Newline results in a little box (same size as other chars)
## Expected Behavior

It should result in a second/third… line.
## Reproduction Instructions

`i3lock --force-clock --datestr="%A %n %d"`
```
i3lock --greetertext="line 1
line 2" 
```

## Environment
Output of `i3lock --version`:
<pre>
i3lock version:
i3lock: version aur-eabfff3 (2019-09-27, branch "tags/aur-eabfff3") © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (which one?)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>
AUR package: i3lock-color-git

### PR DESCRIPTION
**Pull request by cmsxbc**
Try to fix #138 

## Description
 - A basic solution for control chars render (\n, \r, \b, \t)

### reproduce

```bash
# any mono font is good.
./i3lock -t -e -f -n --no-verify \
    --greeter-pos=1200:500 \
    --greeter-font="Cascadia Code" \
    --greeter-text="A example
$(printf 'newline\nnewline')
$(printf 'carriage\rreturn')
$(printf 'newline\r\nreturn')
$(printf 'tab\ttab')
$(printf 'backspace\bbackspace')
$(printf '\rdef    def')
$(printf 'tabtab\ttab')
$(printf 'tabtabtab\ttab')"
```

#### before fix.
40639034-D623-4787-978B-FB434A7417D5

#### after fix.
D09B2B22-AC0E-4174-9C5D-C384BDD04D7B

## Release notes

Notes: Support basic control chars.(\n \r \b \t)

### CODE REVIEW

**Comment by Raymo111** [comment]
This looks great. Can you add `\t` support as well, or would that be too difficult?

**Comment by cmsxbc** [comment]
> This looks great. Can you add `\t` support as well, or would that be too difficult?

Yep, I will have a try, but i don't know the exactly behavior of `\t` yet, especially  when the font is not monospace.
Or maybe I could just replace `\t` with 2 spaces (or 4, 8 or any other user configured) ?

**Comment by Raymo111** [comment]
Actually you know what, I don't think tab is very useful or necessary. People can just just multiple spaces.

**Comment by cmsxbc** [comment]
> Actually you know what, I don't think tab is very useful or necessary. People can just just multiple spaces.

So do I. I just have implemented a `\t` with same behavior as `printf` in `c`

**Review by Raymo111 — CHANGES_REQUESTED** [review]
I like that this works without printf as well (just put the characters in a script). Nice job. Can you document your changes in the manpage (and bump the manpage date to Sep 2021) please?

**Review by Raymo111 — CHANGES_REQUESTED** [review]
More importantly, bug: when there's a tab character immediately after a newline the 2nd line goes all the way to the left of the screen:
2021-09-19-011325_3840x2160_scrot

**Comment by cmsxbc** [comment]
Done, and I'm not good at  English, please fix me if there is any unreadable thing.

**Review by Raymo111 — APPROVED** [review]
LGTM

**Comment by ShadiZade** [comment]
Hey, This just doesn't work for me. I even used your exact same example code, and the problem in your first image still shows up. Here's my code:

```
numofdays=$(date +"%j")
numofweeks=$(echo "scale=1; $numofdays/7" | bc )
i3lock -kef -c aa2200ff --radius 150 --ring-width 5.0 --ring-color=000000ff \
	 --ringver-color=000000ff --insidever-color=00000000 --ringwrong-color=000000ff \
	 --insidewrong-color=00000000 --keyhl-color=ffffffff --bshl-color=aa2200ff \
	 --date-font="Inconsolata Semi Condensed SemiBold" --verif-font="Inconsolata Extra Condensed ExtraBold" \
	 --time-font="Inconsolata Extra Condensed ExtraBold" --layout-font="Inconsolata Extra Condensed ExtraBold" \
	 --wrong-font="Inconsolata Extra Condensed ExtraBold" --wrong-text="INCORRECT" --verif-text="UNLOCKING" \
	 --noinput-text="" --verif-size=22 --wrong-size=22 --time-size=75 --date-size=18 \
	 --date-str="%a, %e %b %Y ("$numofweeks" weeks)" \
	 --greeter-text="A example
	 $(printf 'newline\nnewline')
	 $(printf 'carriage\rreturn')
	 $(printf 'newline\r\nreturn')
	 $(printf 'tab\ttab')
	 $(printf 'backspace\bbackspace')
	 $(printf '\rdef    def')
	 $(printf 'tabtab\ttab')
	 $(printf 'tabtabtab\ttab')" \
	 --no-verify
```


Here's the info
`i3lock: version 2.13.c.4`
`zsh 5.9 (x86_64-pc-linux-gnu`
`Kernel: 5.18.12-3-MANJARO `
`awesome v4.3`

**Comment by Raymo111** [comment]
@ShadiZade try with Bash? (it works for me)
Check your bash version as well.

**Comment by ShadiZade** [comment]
@Raymo111 Nope, doesn't work with bash either.
`GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`

**Comment by Raymo111** [comment]
I'm on the same version of bash. What happens when you run it as a script after adding `#!/bin/bash` to the top?

**Comment by ShadiZade** [comment]
same thing.

**Comment by Raymo111** [comment]
Sorry, not sure then. I copy-pasted your code into a blank bash script and it worked...

**Comment by cmsxbc** [comment]
@ShadiZade I think this fix is not included in `2.13.c.4` which released at June 5, 2021. And this fix merged into master at Jan 11, 2022.

**Comment by ShadiZade** [comment]
@cmsxbc how come the AUR package is so far behind? 

P.S. I tried installing i3lock-color-git from the AUR, and it threw me a bunch of errors about the `--no-verify` flag. the `\n` worked though.

**Comment by ShadiZade** [comment]
for the record, this is the version I have... I'm not sure about the Jan 11 thing since it says that it was updated on Jan 24.
```
Repository      : aur
Name            : i3lock-color
Keywords        : i3  i3lock  i3wm  lock
Version         : 2.13.c.4-1
Description     : The world's most popular non-default computer lockscreen.
URL             : https://github.com/Raymo111/i3lock-color
AUR URL         : https://aur.archlinux.org/packages/i3lock-color
Groups          : None
Licenses        : MIT
Provides        : i3lock  i3lock-color
Depends On      : xcb-util-image  pam  libev  cairo  libxkbcommon-x11  libjpeg-turbo  xcb-util-xrm  pkgconf
Make Deps       : None
Check Deps      : None
Optional Deps   : None
Conflicts With  : i3lock  i3lock-color-git
Maintainer      : Raymo111
Votes           : 37
Popularity      : 1.104701
First Submitted : Mon 19 Oct 2020 12:53:40 AM EEST
Last Modified   : Mon 24 Jan 2022 08:33:04 AM EET
Out-of-date     : No

```

**Comment by ShadiZade** [comment]
@Raymo111 I went ahead and built the package manually. It worked (looks like @cmsxbc was right), but only in the greeter text. Was it never meant to work in the date string?

**Comment by Raymo111** [comment]
@ShadiZade I'm using i3lock-color-git from the AUR and everything works, no errors with the no-verify flag. I haven't created a new release in a year now hence the discrepancy between the packages/releases and self-built ones, I'll spin up a new release next week.

**Comment by ShadiZade** [comment]
Very well, thanks for your efforts. One last question: is the linebreak supposed to work in the date string, or only in the greeter text?

**Comment by Raymo111** [comment]
It's supposed to work everywhere.

**Pull request merged**
