### PR TITLE
Use 32bit-deep drawables 

### PR DESCRIPTION
**Pull request by bendardenne**
This allows setting a background color with an alpha channel.

In combination with compton, this allows for fast blurring (by just setting a transparent color and letting compton do the blurring).

### CODE REVIEW

**Comment by Raymo111** [comment]
Looks interesting. I'll review and test everything.

**Comment by Raymo111** [comment]
Would we be able to have an option to keep the screen static as well?

**Comment by bendardenne** [comment]
> Would we be able to have an option to keep the screen static as well?

Not if you want to let the compositing manager do it.  You can still use `i3lock -B` for that, I guess.

**Comment by Raymo111** [comment]
@bendardenne `./i3lock -c 22222288 --no-verify` doesn't seem to work? It's still opaque. Also, how does blurring work? If I understand correctly the 4th bit just sets alpha/transparency?

**Comment by bendardenne** [comment]
Which compositor are you using? 

Maybe I should clarify the idea, which is only to introduce transparency in i3lock. To get transparent windows, you need a compositor running.

Then, some compositors (compton & forks) can be configured so that when they see transparency, they don't just apply transparency but also do blurring when they composethe window  with whatever is behind. So efficient blurring comes as a bonus of having true transparency within i3lock, **if** you use a compositor which can do blurring.
The idea is not to replace the `-B` option which can still be useful if you cannot / don't want to have a compositor with blurring.

**Comment by Raymo111** [comment]
Ohh I see. That makes so much sense. I'm not using any compositor that I know of, just KDE Plasma/kwin. Can you add a section to the manpage right under the 4-bit alpha to describe compositors and which ones work? Thanks. Also... in my case, how would I get and use a compositor?

**Comment by bendardenne** [comment]
Sure I'll add some explanations to the documentation.

I don't know anything about kwin to be honest. From some quick googling, kwin handles compositing itself but I don't know if/how you could get this to work with it. Maybe first try to get regular windows transparent, like konsole or whichever terminal you use.

**Comment by Raymo111** [comment]
Konsole and other windows work with transparency. Honestly I have no idea how kwin does it, I don't play around with compositors nearly enough to be familiar.

**Review by Raymo111 — APPROVED** [review]
Looks good to me.

**Comment by bernb** [comment]
Could you provide an example how to produce the desired effect with compton? From my understanding it should be possible to utilize compton even if not used normally.
I however struggle to produce a strongly blurred background that prevents a human from being able to read the screen.

Screenshot based blurring have been quite slow for me (1 UHD, 1 FHD Screen), while using compton works without any noticeable delay.

As a workaround, as I do not use a composite manager atm, I use the following:
```
compton --blur-background --blur-kern 11x11gaussian & i3lock -n -c 222222AA && kill $!
```
This starts compton together with i3lock-color and terminates compton when i3lock returns.

**Pull request merged**
