### PR TITLE
New --bar-count option to replace --bar-width

### LINKED ISSUE #196: Bar indicator spans over multiple displays
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

The bar indicator spans over multiple displays, this is especially visible when two displays are offsetted, where one when of them there would just be bars floating in the middle

2021-01-17-222657_4480x1900_scrot

As shown in the screenshot, the display on the right side has a floating bar in the middle.

## Expected Behavior

The bar should stay in its own display without expanding into neighboring displays.

## Reproduction Instructions

The config of the bars I am using:
```
i3lock --bar-indicator --bar-position=y+h --bar-direction=1
```

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.12.c.5 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2020 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[x] AUR package (which one?) - aur/i3lock-color
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

### PR DESCRIPTION
**Pull request by Rio6**
Fixes #196

## Description
This PR adds a --bar-count option to specify how many minibars to draw on each screen (and deprecates --bar-width). It makes it easier to draw bars on multiple screens with different resolutions. I also rewrote the bar drawing function a bit to handle screen positions.

--bar-width still works the same, except a deprecation warning will show on stderr.

### Screenshots/screencaps
2021-01-24-131249_4480x1900_scrot

## Release notes

Notes: --bar-width is deprecated by --bar-count to make bar indicators work better on multi-screens.

### CODE REVIEW

**Comment by Raymo111** [comment]
Your code looks good so far (haven't had a chance to test it yet). I'm debating whether or not to just deprecate bar entirely though. I've never heard of anyone using it (until you), and if you search the commit history for "bar" there's literally more bug fixes than working code. Since you're the first bar user I've heard of, would you mind weighing in on this? Thanks for contributing!

**Comment by Rio6** [comment]
As someone who uses the bar, having the bar staying is ofc preferred for me 😆. That being said, if you have a good reason to remove it, then it's not probably worth holding it for the few users (I hope there are more than  just me :P) who wants it.

I did almost completely rewrite the draw_bar function in this PR to hopefully make it easier to maintain. But I'm totally fine if it's removed, since I can just use my own fork. (There do be a lot of i3lock forks out there).

Anyways, not much opinion from me.

**Comment by Raymo111** [comment]
@Rio6 I have no reason to remove it besides:
1) I don't use it
2) I haven't heard of anyone using it
3) There might be bugs in it.

I think 1 is a ridiculous reason, 2 does not reflect all users, and 3 can be overcome with PRs from actual bar users like you. Hmm prolly best to keep it then.

**Comment by Raymo111** [comment]
@Rio6 can you give me edit perms to your PR? I'd like to make a few small changes (in particular 65536->65535 for max count).

**Comment by Rio6** [comment]
Sure, if I can find the setting XD.

65536 is just some nice large number that I hope no one will ever reach as a limit to calloc, no real reason for that particular number other than it being 2^16.

Update: found the checkbox

**Comment by Raymo111** [comment]
Thanks. Yeah it's just cause I'm paranoid of setting something to 2147483648 for example, because overflows in 16-bit unsigned.

**Comment by Raymo111** [comment]
Ok couple things:
1. I just reformatted the new code in `i3lock.c` to be more readable. Build test passes but I might have broken some code you wrote, so please do make more edits if I did break something.
2. If the `bar_width` option is used alongside bar_count then we'd have to ignore one and fprintf an error right? I couldn't find that anywhere.

**Comment by Rio6** [comment]
1. Ok I will test it
2. Since --bar-width is getting deprecated, I kind of assumed that anyone who uses the new --bar-count flag wouldn't use the old --bar-width at the same time, and if they do it's their fault :P. The deprecation warning will show anyways. It simplifies the code a bit. But it's reasonable to make --bar-count overwrite --bar-width. I can add it.

**Comment by Raymo111** [comment]
Great, thanks! (To both points)

**Comment by Rio6** [comment]
The newest commit seem to be working. I also updated the default bar count to 10 so it's not one big bar by default.

**Review by Raymo111 — APPROVED** [review]
Ok, finally had the time to look over all your code. LGTM.

**Comment by Raymo111** [comment]
Since you're now the one person that's the most familiar with the bar code, is it cool if I make you responsible for any future bar issues, PRs, and features?

**Comment by Rio6** [comment]
Yeah that's all good. BTW is there a reason to make min bar count to be 2 and not 1? I feel making one bar across the screen possible is still a nice thing to have (unless it breaks something?)

**Comment by Raymo111** [comment]
Great! Oh, I was just thinking no one would ever want 1 bar and it could be treated like an error (i.e. why is my bar option not showing bars). I do agree with you though - lemme revert my last commit.

**Comment by Rio6** [comment]
Sounds good, thanks!

**Comment by Raymo111** [comment]
Aight. I just went over the backlog of PRs and issues (yay!), and I think I'll push a new release tomorrow.

**Pull request merged**
