### PR TITLE
Autotools

### PR DESCRIPTION
**Pull request by PandorasFox**

### CODE REVIEW

**Comment by PandorasFox** [comment]
Finally getting around to merging in the SSE3 stuff from @sebastian-frysztak from last year. Dunno why I never got around to that.

**Comment by frysztak** [comment]
I'm flattered that my code is going to be used, but I think you may have merged wrong branch. https://github.com/sebastian-frysztak/i3lock-color/tree/box-blur --- this is, at least in my mind, final version. I removed all of my SSSE3 and AVX experiments, because SSE2 gave the best results and is mostly widely adopted.

**Comment by PandorasFox** [comment]
Hm, I'll poke at that now - it seems on my system that SSE3 performs the best, but I'll give this one a shot.

I just had a `blur` branch sitting in my repo and that was what I went off of; I forgot to go check your repo

**Comment by PandorasFox** [comment]
...that's the code I already had in my repo. I feel kinda dumb now.

Time to revert a few commits, I guess.

**Comment by PandorasFox** [comment]
Alright, I reverted back to what's in the box-blur branch (and to what I had before), with a small fix to make the new address sanitizer stop exploding on an occasional out-of-bounds read/write.

I'm going to poke some more at the SSE3 stuff, since at least on my Ryzen rig, it performs a lot better.

**Comment by frysztak** [comment]
My concerns regarding SSSE3 aren't regarding speed (I think it was faster on my rig too), they're regarding quality. With SSE2 we're using floating point numbers whereas with SSSE3 -- small integers that tend to overflow/underflow. Resulting image looks much worse.

It might be worth looking into OpenGL acceleration, I dunno.

**Comment by PandorasFox** [comment]
I didn't notice much difference in quality, but I'll take some stabs at it all and see how it works out.

**Comment by PandorasFox** [comment]
Yeah, SSE3 has some issues with colors becoming wildly darker or brighter, depending on the sigma level. I'm just going to drop that for now and work on some cairo stuff, and then OpenGL stuff will be next on the list.

**Pull request merged**
