### PR TITLE
add --no-verify option, add XF86Sleep to --pass-power-keys

### PR DESCRIPTION
**Pull request by martin2250**
Hi @PandorasFox,

I have two small changes for i3lock-color:
- a `--no-verify` option that unlocks the screen on any password. Useful for trying out new configs while setting up `i3lock` (and on PCs where it serves more as a decoration than actual access control)
- `--pass-power-keys` also passes XF86Sleep

I know I probably should have split this into two pull requests, if you insist I can try to work out how to do that.

Hope you're okay with these changes.
Best,
Martin

### CODE REVIEW

**Comment by umute97** [comment]
+1 would love to see this in the future!

**Comment by Raymo111** [comment]
@martin2250 I'm ok with XF86Sleep being merged. For the no-verify option, can you add more documentation stressing that this should only be used for testing? Also, remove the -x option, as that will be too easy to forget and leave into an actual configuration. I'll be happy to merge your PR once these things are fixed.

**Comment by martin2250** [comment]
@Raymo111 thanks for maintaining this project! Should be all good now.

**Comment by Raymo111** [comment]
Excellent. Thanks for contributing!

**Pull request merged**
