### PR TITLE
Use system-local-login for PAM on Arch/Gentoo

### LINKED ISSUE #201: Use system-local-login instead of system-auth for PAM
## This issue is a....

<pre>
[ ] Bug
[ X ] 3rd party configuration error
</pre>

## Current Behavior

i3lock currently uses `include system-auth` for PAM by default on Arch & Gentoo.

## Expected Behavior

i3lock should use `system-local-login` instead as it's meant for local logins.

## Reproduction Instructions

I currently use `pam_u2f.so` to get passwordless login with a hardware token. I restrict this functionality to local logins by configuring `system-local-login`. I cannot configure `system-auth` as it is also inherited by `system-remote-login` which affects stuff like SSH. i3lock ignores my passwordless configuration as it instead checks `system-auth` instead of `system-local-login`.

## Environment
Output of `i3lock --version`:
<pre>
i3lock: version 2.13.c.1 © 2010 Michael Stapelberg, © 2015 Cassandra Fox, © 2020 Raymond Li
</pre>

Where'd you get i3lock-color from?

<pre>
[ X ] AUR package (i3lock-color)
[ ] Built from source yourself
[ ] Other (Please describe in detail)
</pre>

### PR DESCRIPTION
**Pull request by msafadieh**
Closes #201

## Description
 - Use `system-local-login` instead of `system-auth` for PAM on Arch/Gentoo

## Release notes

Notes:
 - Use `system-local-login` instead of `system-auth` for PAM on Arch/Gentoo

### CODE REVIEW

**Comment by Raymo111** [comment]
I'll merge this once I test on Arch. I'm assuming you use, and have tested this on, Gentoo?

**Comment by msafadieh** [comment]
Nope, sadly just another Arch user here.

**Comment by Raymo111** [comment]
Lool ok I'll run it in a VM then ig. I'm actually on Windows right now (need it for school and too lazy to dual-boot/switch computers all the time) so I can test both Ubuntu and Arch through WSL, but I'm petrified of Gentoo and what it could do to my system so haven't tried Gentoo on WSL yet.

**Comment by Raymo111** [comment]
I've been trying to test your changes all day but CRLF is screwing me over. Ugh.

**Comment by msafadieh** [comment]
Any way I could help?

**Comment by Raymo111** [comment]
I just realized I had this comment typed out and never sent it:
---
Ok I sorted out the CRLF stuff. Windows is a terrible OS to develop for Linux on (but great for testing). I tested through Arch and Ubuntu on WSL and am now trying to setup Gentoo in a VM to test there.
---
5 hours later...

So I can't setup Gentoo. I'm too noob. Since it works on Arch and Gentoo's wiki mentions supporting `system-local-auth`, we can merge this for now. If some gentoo user faces issues then we can figure something out if an when that happens.

**Review by Raymo111 — APPROVED** [review]
Good to go.

**Pull request merged**
