### PR TITLE
Fix key group

### LINKED ISSUE #115: Update keyboard layout indicator on change
## This issue is a....

<pre>
[x] Bug
[ ] Other kind of issue (Please describe in detail)
</pre>

## Current Behavior

When I hit hotkeys for switching layout it changes but the on-screen indicator doesn't.

## Expected Behavior

When switch keyboard layout, the on-screen indicator should show the new layout instead of the old one.

## Reproduction Instructions
`--keylayout 2`

## Environment
Output of `i3lock --version`:
<pre>
i3lock version:
i3lock: version 2.12.c-non-git © 2010 Michael Stapelberg, © 2015 Cassandra Fox
</pre>

Where'd you get i3lock-color from?

<pre>
[ ] AUR package (which one?)
[ ] Built from source yourself
[x] `gig` Gentoo Overlay
</pre>

### PR DESCRIPTION
**Pull request by andremarcais**
Fixes/Closes #115

## Description
 - Displays effective key group.
 - Re-displays on xkb state change.

## Release notes

Notes: Bug fix for effective key group display.

### CODE REVIEW

**Comment by andremarcais** [comment]
As of now there is no mutex on the ``layout_text`` global (nor is there on any of the globals like ``unlock_state`` and ``modifier_string``) which is potentially a problem for ``--redraw-thread``.

**Comment by Raymo111** [comment]
@andremarcais what exactly is a key group? I just want to be certain before merging this.

**Comment by andremarcais** [comment]
In X, one of four key groups is active. X maps a keycode (which represents a physical key) and group to a character.

In higher level user configuration the user may, e.g., set the layout to ``us,fr``, which causes Group 1 to be mapped to ``us`` characters and Group 2 to be mapped to ``fr`` characters. The active group determines what character results from a keycode.

Using options like ``grp:shifts_toggle`` makes switching the active group easy.

My explanation oversimplifies this a little bit. [This page](https://www.x.org/wiki/guide/hutterer-kbd/) explains this in greater detail.

**Comment by Raymo111** [comment]
I see. Alright, I'll merge the PR.

**Review by Raymo111 — APPROVED** [review]
Approved based on working screencap and good feedback from other users.

**Pull request merged**
