### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by h3ct0rjs**
Improves the installation instruction, sometimes you don't know what to do with the *.c and *.h :smile:

Regards, 
Hector F.

### CODE REVIEW

**Comment by PandorasFox** [comment]
Really shouldn't have to put in steps about how to clone, make, and install - you should either be using a packaged version for your distro, or you should know how to build and install.

**Comment by PandorasFox** [comment]
I'm not really a fan of telling people what to do and having them blindly paste in commands - I'd much rather have them understand what they're doing and why, especially if they're using forked software.

**Comment by h3ct0rjs** [comment]
Hi @chrjguill the fact that you add the instructions doesn't mean that you don't know what you're doing, this is a step required and to me seems okay to explain this to new users. besides I'm doing this because somebody in an irc chat just tell that he didn't see the instruction for the installation. Anyway you're the owner. I was wondering if this will be in the next release of the official i3wm, may @stapelberg

**Comment by stapelberg** [comment]
We’re not looking to include build instructions in the upstream i3lock README. In general, the i3 project stanza is that end users should use distribution packages instead of having to compile software on their own.

**Comment by PandorasFox** [comment]
> In general, the i3 project stanza is that end users should use distribution packages instead of having to compile software on their own.

Pretty much this; you should either be using a packaged version, or you should know what you're doing - there shouldn't be any middle ground, __especially__ since this is a fork (and a fork of a screen locker - you don't want to fall behind if there's a bug that affects security).

That all being said, I'll add some links to packages for different distros when I have some time. I actually use [this package](https://aur.archlinux.org/packages/i3lock-color-git) on my systems for day-to-day use.

**Pull request closed without merging**
