### PR TITLE
Blur support

### PR DESCRIPTION
**Pull request by frysztak**

### CODE REVIEW

**Comment by PandorasFox** [comment]
some notes on speeds on my craptop:

```
arcana@archana:~/boxblur$ time (scrot in.png && ffmpeg -loglevel quiet -y -i in.png -vf "gblur=sigma=8" out.png && ./i3lock -i ./out.png)

real	0m0.408s
user	0m0.407s
sys	0m0.040s
arcana@archana:~/boxblur$ time (scrot in.png && ffmpeg -loglevel quiet -y -i in.png -vf "gblur=sigma=8" out.png && ./i3lock -i ./out.png)

real	0m0.416s
user	0m0.427s
sys	0m0.023s
arcana@archana:~/boxblur$ time (scrot in.png && ffmpeg -loglevel quiet -y -i in.png -vf "gblur=sigma=8" out.png && ./i3lock -i ./out.png)

real	0m0.427s
user	0m0.427s
sys	0m0.037s
arcana@archana:~/boxblur$ time (scrot in.png && ffmpeg -loglevel quiet -y -i in.png -vf "gblur=sigma=8" out.png && ./i3lock -i ./out.png)

real	0m0.418s
user	0m0.417s
sys	0m0.037s
arcana@archana:~/boxblur$ time (scrot in.png && ffmpeg -loglevel quiet -y -i in.png -vf "gblur=sigma=8" out.png && ./i3lock -i ./out.png)

real	0m0.406s
user	0m0.407s
sys	0m0.027s
arcana@archana:~/boxblur$ time ./i3lock -B 8

real	0m0.217s
user	0m0.197s
sys	0m0.013s
arcana@archana:~/boxblur$ time ./i3lock -B 8

real	0m0.196s
user	0m0.173s
sys	0m0.020s
arcana@archana:~/boxblur$ time ./i3lock -B 8

real	0m0.217s
user	0m0.200s
sys	0m0.010s
arcana@archana:~/boxblur$ time ./i3lock -B 8

real	0m0.216s
user	0m0.197s
sys	0m0.010s
```

My desktop hits around 70ms with this, and averages 200ms - so speedups of 2-3x (most likely dependent on resolution; my desktop has ~4x as many pixels as my laptop) is really good!

I'm pretty happy with this. Thanks!

**Comment by dikiaap** [comment]
Hey, I had a problem when compiling from new commits.
GCC v5.4.0 20160609
Ubuntu 16.04.2 32bit

https://gist.github.com/dikiaap/7c902bdbf18cdd41024277cf9596622f

**Comment by PandorasFox** [comment]
Hm, do you have SSE compatible hardware?

I've got gcc v 6.3.1, but I have 5.4 in a ubuntu VM somewhere. I'll try that out in a few.

**Comment by PandorasFox** [comment]
Compiling it works fine in Xubuntu 16.04LTS with GCC v 4.8.x, so I'm not quite sure what the problem is.

**Comment by dikiaap** [comment]
I was checking /proc/cpuinfo. The results is
model name: AMD E-300 API with Radeon(tm) HD Graphics
In flags section I have sse sse2 ssse3 sse4a

**Comment by PandorasFox** [comment]
Try with [this makefile](https://gist.github.com/chrjguill/078f079bac7f2f24473cf066f304a9fa)

**Comment by dikiaap** [comment]
@chrjguill yeah. It's works right now, but I got some errors.

https://gist.github.com/dikiaap/18d479124610573b9f52648e469ebc3f

**Comment by frysztak** [comment]
@dikiaap: those are warnings, not errors.
@chrjguill: I forgot to explicitly add `-msse2` flag to the Makefile. On Arch it's apparently added automatically. `-msse4.1` is not necessary.  `-msse2` doesn't have to be applied to every source file, adding it to `SIMD_CFLAGS` will do.

**Comment by PandorasFox** [comment]
Ah, alright. I just tried that on one of my VMs real fast and it seemed to work, but I'll refine it a bit later today

**Comment by PandorasFox** [comment]
And yeah, those warnings are actually pretty normal. Sometimes they show up, sometimes they don't. I never got around to cleaning them up since they don't matter once it's all linked iirc.

**Pull request merged**
