### PR TITLE
Added i3lock-color-debian package

### PR DESCRIPTION
**Pull request by barnumbirr**
Added  i3lock-color-debian package to README.

### CODE REVIEW

**Comment by Raymo111** [comment]
@barnumbirr I've been trying to get i3lock-color published to Debian package manager, would you mind integrating your repo into i3lock-color? What changes did you make for Debian?

**Comment by barnumbirr** [comment]
Hey,
I wouldn't mind at all. Would a simple PR work for you? Changes compared to what exactly?
Cheers.

**Comment by Raymo111** [comment]
Sure, a PR would work. I meant changes compared to the main i3lock-color repo. What did you change for Debian?

**Comment by barnumbirr** [comment]
You know what: I'm an idiot and didn't even think of using the `i3lock` as a base and just went from scratch 🤦.  I guess it's mainly the package name as well as a couple of dependencies in the `debian/control` file.

**Comment by Raymo111** [comment]
uhh what? Didn't you use the i3lock-color code and modify it? Did you rewrite everything yourself?

**Comment by barnumbirr** [comment]
The package does use the code from `i3lock-color` but you're comment made me think that I could have used the `debian` files of the original `i3lock` repository as inspiration. I didn't and through trial and error, figured out how to package `i3lock-color` on my own.

**Comment by Raymo111** [comment]
Oh ok, so since you used the i3lock-color files, you'll just be adding additional debian stuff, right? So you can PR without touching the rest of the code, if I understand correctly?

**Comment by barnumbirr** [comment]
Yes, I'll just need to create a PR that adds all the necessary files in a new `debian` directory. I'll do that tomorrow.
Cheers.

**Comment by Raymo111** [comment]
Awesome! I'll close this PR for now. Thank you! Also, if you can get it published to apt that would be added awesomeness.

**Pull request closed without merging**
